### POST send code
POST http://localhost:8082/send-code
Accept: text/plain
Content-Type: application/json
X-API-KEY: test-token
x-correlator: cfb2f91a-f946-4141-94c2-82a33bb2f198
{
    "phoneNumber" : "+48123456789",
    "message" : "{{code}} is your short code to authenticate with Cool App via SMS"
}

### POST verify code
POST http://localhost:8082/validate-code
Accept: text/plain
Content-Type: application/json
X-API-KEY: test-token
x-correlator: cfb2f91a-f946-4141-94c2-82a33bb2f198
{
    "authenticationId" : "cfb2f91a-f946-4141-94c2-82a33bb2f198",
    "code" : "V95E"
}